version: "3.9"

services:
  api:
    build: .
    container_name: viteapi
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - neo4j
    command: sh -c "pnpm dev"

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:5
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4j
    volumes:
      - neo4j_data:/data

volumes:
  mongo_data:
  neo4j_data: 
