name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier (write)
        run: npx prettier --write .

      - name: Run ESLint (fix)
        run: npx eslint src --ext .ts,.tsx --fix

      - name: Run tests
        run: npm test
